### ISSUE TITLE
Cannot create bucket on Heroku with kinto-pusher enabled.

### ISSUE THREAD

**Issue by MadeMyDay** [Kinto/kinto-heroku#20]
Hi, first of all: Thank you for this project, playing with it since 3 days and I am absolutely thrilled to use it in my application ;-)

I managed to set up a Heroku app (new to Python, so took a while) and now everything seems to be fine even the Pusher integration worked.

But now I struggle with creating another bucket beside the default bucket. I always get this error from the server:

`http.js?bfa9:190 Uncaught (in promise) Error: HTTP 403 Forbidden: Resource access is forbidden for this user (This user cannot access this resource.)`

So I thought perhaps buckets are not auto-created with kinto.js. So I tried to create a bucket first with (simplified):

```
var kintobucket = "testbucket";
var kintoheaders = {
	Authorization: "Basic " + btoa("user:pass")
}
var kinto = new Kinto({
       remote: "https://mykintoappID.herokuapp.com/v1",
       headers: kintoheaders 
});
const testserver = kinto.api.createBucket("another")
	 	.then(function(data){
	 		console.log("server data",data)
		});
```

which gives me:

`Uncaught (in promise) Error: HTTP 500 Internal Server Error: Internal Server Error (A programmatic error occured, developers have been informed.)(…)`

which is the exact error I get if I try to create the bucket through Kinto Admin.

Any thoughts? Is it just not possible on a free Heroku Account to create several buckets? 

Out of curiosity: Would kinto.js normally create the bucket if it doesn't exist?

Thanks in advance!

**Comment by Natim** [comment]
Hello @MadeMyDay 

Thanks for using Kinto.

> Would kinto.js normally create the bucket if it doesn't exist?

No, the bucket creation is automatic only with the default bucket.
If you plan on sharing data between user you should create the bucket as part as the application setup so that you have administrator permissions on it.

> HTTP 500 Internal Server Error

This is not supposed to happen, can you look at your Heroku log and give use the traceback of the error on the server side?

> Is it just not possible on a free Heroku Account to create several buckets?

Yes it should be possible.

Permission to create buckets is given by the  `kinto.bucket_create_principals = system.Authenticated` config. You might want to change that to use your administrator user ID.

**Comment by MadeMyDay** [comment]
Hi @Natim ,

Thanks for this quick response!

> This is not supposed to happen, can you look at your Heroku log and give use the traceback of the error on the server side?

The logs for trying to PUT the new bucket:

```2017-02-21T15:24:51.461663+00:00 heroku[router]: at=info method=PUT path="/v1/buckets/testbucket" host=myherokukintoapp.herokuapp.com request_id=66c4c611-bb78-40a6-84db-33b8af84f37b fwd="109.193.15.50" dyno=web.1 connect=1ms service=46ms status=500 bytes=489
2017-02-21T15:24:51.459213+00:00 app[web.1]:     response = handler(request)
2017-02-21T15:24:51.459211+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
2017-02-21T15:24:51.459199+00:00 app[web.1]: ERROR:kinto.core.views.errors:"PUT   /v1/buckets/testbucket" ? (? ms) 'collection_id' agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36 authn_type=basicauth collection_id=bucket collection_timestamp=1487629490785 errno=110 exception=Traceback (most recent call last):
2017-02-21T15:24:51.459214+00:00 app[web.1]:     reraise(*exc_info)
2017-02-21T15:24:51.459214+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 119, in tm_tween
2017-02-21T15:24:51.459215+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 105, in tm_tween
2017-02-21T15:24:51.459217+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/transaction/_manager.py", line 131, in commit
2017-02-21T15:24:51.459217+00:00 app[web.1]:     return self.get().commit()
2017-02-21T15:24:51.459218+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/transaction/_transaction.py", line 296, in commit
2017-02-21T15:24:51.459216+00:00 app[web.1]:     manager.commit()
2017-02-21T15:24:51.459221+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/transaction/_transaction.py", line 367, in _callBeforeCommitHooks
2017-02-21T15:24:51.459220+00:00 app[web.1]:     self._callBeforeCommitHooks()
2017-02-21T15:24:51.459222+00:00 app[web.1]:     hook(*args, **kws)
2017-02-21T15:24:51.459223+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kinto/core/events.py", line 76, in _notify_resource_events_before
2017-02-21T15:24:51.459223+00:00 app[web.1]:     request.registry.notify(event)
2017-02-21T15:24:51.459224+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pyramid/registry.py", line 91, in notify
2017-02-21T15:24:51.459226+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/zope/interface/registry.py", line 442, in subscribers
2017-02-21T15:24:51.459225+00:00 app[web.1]:     [ _ for _ in self.subscribers(events, None) ]
2017-02-21T15:24:51.459227+00:00 app[web.1]:     return self.adapters.subscribers(objects, provided)
2017-02-21T15:24:51.459228+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/zope/interface/adapter.py", line 598, in subscribers
2017-02-21T15:24:51.459230+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pyramid/config/adapters.py", line 130, in subscriber_wrapper
2017-02-21T15:24:51.459231+00:00 app[web.1]:     return derived_subscriber(*arg)
2017-02-21T15:24:51.459231+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pyramid/config/adapters.py", line 103, in derived_subscriber
2017-02-21T15:24:51.459232+00:00 app[web.1]:     return subscriber(arg[0])
2017-02-21T15:24:51.459233+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kinto_pusher/listener.py", line 12, in __call__
2017-02-21T15:24:51.459235+00:00 app[web.1]: KeyError: 'collection_id' lang=de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2 uid=5741b99cc5b467903f9a37432da59f6d227354acbca1834bdd1dea1dd350a8e
2017-02-21T15:24:51.459233+00:00 app[web.1]:     channel = self.channel.format(**event.payload)
2017-02-21T15:24:51.459229+00:00 app[web.1]:     subscription(*objects)```

> Permission to create buckets is given by the kinto.bucket_create_principals = system.Authenticated config. You might want to change that to use your administrator user ID.

Okay, I guess that seems rather to be the problem. But: Where do I have to set this? Can I set it in kinto.ini? And what do you mean with administrator user ID? The Heroku one? Sorry for the dumb questions, but Python is completely new to me ;-)

**Comment by Natim** [comment]
I guess there is an issue with the current kinto_pusher release. I would enjoin you to deactivate the kinto_pusher and reactivate it after having created your bucket.

I created https://github.com/Kinto/kinto-pusher/issues/19 about that.

**Comment by MadeMyDay** [comment]
Okay, thanks!  I'll try that this evening and will report.

**Comment by Natim** [comment]
It should be fixed with kinto-pusher 0.5.0 can you upgrade it on your instance and confirm?

**Comment by MadeMyDay** [comment]
That worked perfectly. Thank you very much!

**Comment by Natim** [comment]
Thank you for using Kinto :) If you can find some room to write an article about why and how you are using Kinto for your project it would be greatly appreciated.

**Comment by MadeMyDay** [comment]
Thank YOU for your help!

> If you can find some room to write an article about why and how you are using Kinto for your project it would be greatly appreciated.

Will definitely do once the project leaves early stage and things are functional in the MVP.
