### ISSUE TITLE
Deploy to Heroku Fails

### ISSUE THREAD

**Issue by searchy2** [Kinto/kinto-heroku#24]
The 1 click deploy to Heroku unfortunately fails.

Error Logs:
```
-----> Python app detected
 !     Python has released a security update! Please consider upgrading to python-3.6.10
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
cp: cannot create regular file '/app/tmp/cache/.heroku/requirements.txt': No such file or directory
-----> Installing python-3.6.0
-----> Installing pip
-----> Installing SQLite3
Sqlite3 successfully installed.
-----> Installing requirements with pip
       Collecting kinto==9.1.2
         Downloading kinto-9.1.2.tar.gz (3.5 MB)
       Collecting SQLAlchemy
         Downloading SQLAlchemy-1.3.15.tar.gz (6.1 MB)
         Installing build dependencies: started
         Installing build dependencies: finished with status 'done'
         Getting requirements to build wheel: started
         Getting requirements to build wheel: finished with status 'done'
           Preparing wheel metadata: started
           Preparing wheel metadata: finished with status 'done'
       Collecting psycopg2>2.5
         Downloading psycopg2-2.8.4.tar.gz (377 kB)
       Collecting zope.sqlalchemy
         Downloading zope.sqlalchemy-1.3-py2.py3-none-any.whl (21 kB)
       Collecting bcrypt
         Downloading bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl (56 kB)
       Collecting colander>=1.4.0
         Downloading colander-1.7.0-py2.py3-none-any.whl (113 kB)
       Collecting cornice
         Downloading cornice-4.0.1-py2.py3-none-any.whl (37 kB)
       Collecting cornice_swagger>=0.5.1
         Downloading cornice_swagger-0.7.0.tar.gz (38 kB)
       Collecting dockerflow
         Downloading dockerflow-2019.10.0-py2.py3-none-any.whl (31 kB)
       Collecting jsonschema
         Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
       Collecting jsonpatch
         Downloading jsonpatch-1.25-py2.py3-none-any.whl (11 kB)
       Collecting logging-color-formatter>=1.0.1
         Downloading logging-color-formatter-1.0.2.tar.gz (4.1 kB)
       Collecting python-dateutil
         Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
       Collecting pyramid<2.0,>=1.9.1
         Downloading pyramid-1.10.4-py2.py3-none-any.whl (325 kB)
       Collecting pyramid_multiauth>=0.8
         Downloading pyramid_multiauth-0.9.0-py2.py3-none-any.whl (13 kB)
       Collecting transaction
         Downloading transaction-3.0.0-py2.py3-none-any.whl (47 kB)
       Collecting pyramid_tm>=2.1
         Downloading pyramid_tm-2.4-py2.py3-none-any.whl (15 kB)
       Collecting requests
         Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
       Collecting waitress
         Downloading waitress-1.4.3-py2.py3-none-any.whl (148 kB)
       Collecting ujson>=1.35
         Downloading ujson-2.0.3-cp36-cp36m-manylinux1_x86_64.whl (174 kB)
       Collecting zope.interface>=3.6.0
         Downloading zope.interface-5.0.1-cp36-cp36m-manylinux2010_x86_64.whl (226 kB)
       Collecting cffi>=1.1
         Downloading cffi-1.14.0-cp36-cp36m-manylinux1_x86_64.whl (399 kB)
       Collecting six>=1.4.1
         Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
       Collecting translationstring
         Downloading translationstring-1.3-py2.py3-none-any.whl (15 kB)
       Collecting iso8601
         Downloading iso8601-0.1.12-py2.py3-none-any.whl (12 kB)
       Collecting venusian
         Downloading venusian-3.0.0-py3-none-any.whl (13 kB)
       Collecting simplejson
         Downloading simplejson-3.17.0.tar.gz (83 kB)
       Collecting importlib-metadata; python_version < "3.8"
         Downloading importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
       Collecting attrs>=17.4.0
         Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
       Collecting pyrsistent>=0.14.0
         Downloading pyrsistent-0.16.0.tar.gz (108 kB)
       Collecting jsonpointer>=1.9
         Downloading jsonpointer-2.0-py2.py3-none-any.whl (7.6 kB)
       Collecting colorama
         Downloading colorama-0.4.3-py2.py3-none-any.whl (15 kB)
       Collecting webob>=1.8.3
         Downloading WebOb-1.8.6-py2.py3-none-any.whl (114 kB)
       Collecting plaster
         Downloading plaster-1.0-py2.py3-none-any.whl (14 kB)
       Collecting plaster-pastedeploy
         Downloading plaster_pastedeploy-0.7-py2.py3-none-any.whl (7.8 kB)
       Collecting hupper>=1.5
         Downloading hupper-1.10.2-py2.py3-none-any.whl (26 kB)
       Collecting zope.deprecation>=3.5.0
         Downloading zope.deprecation-4.4.0-py2.py3-none-any.whl (10 kB)
       Collecting certifi>=2017.4.17
         Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
       Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
         Downloading urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
       Collecting idna<3,>=2.5
         Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
       Collecting chardet<4,>=3.0.2
         Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
       Collecting pycparser
         Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
       Collecting zipp>=0.5
         Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)
       Collecting PasteDeploy>=2.0
         Downloading PasteDeploy-2.1.0-py2.py3-none-any.whl (17 kB)
       Building wheels for collected packages: kinto, SQLAlchemy, psycopg2, cornice-swagger, logging-color-formatter, simplejson, pyrsistent
         Building wheel for kinto (setup.py): started
         Building wheel for kinto (setup.py): finished with status 'done'
         Created wheel for kinto: filename=kinto-9.1.2-cp3-none-any.whl size=2465580 sha256=8d65951836f94e4c63e3faa9625d718f33827b2f47bdc93400b3f9551546cb7b
         Stored in directory: /tmp/pip-ephem-wheel-cache-1klnwuaa/wheels/3d/3e/51/8967c3ae0b6a7e4e10ed8d24f18085de34cba7a098abf99af4
         Building wheel for SQLAlchemy (PEP 517): started
         Building wheel for SQLAlchemy (PEP 517): finished with status 'done'
         Created wheel for SQLAlchemy: filename=SQLAlchemy-1.3.15-cp36-cp36m-linux_x86_64.whl size=1230237 sha256=8c693ad19ccafcb797f2ae148753a798bc0fc5b62f2b3a2866305a2a444fcc4e
         Stored in directory: /tmp/pip-ephem-wheel-cache-1klnwuaa/wheels/4a/1b/3a/c73044d7be48baeb47cbee343334f7803726ca1e9ba7b29095
         Building wheel for psycopg2 (setup.py): started
         Building wheel for psycopg2 (setup.py): finished with status 'done'
         Created wheel for psycopg2: filename=psycopg2-2.8.4-cp36-cp36m-linux_x86_64.whl size=446639 sha256=e7aa0371b787564e69b1da17b4efbba61fbb3b734bcf276af2c12be1b8cacc46
         Stored in directory: /tmp/pip-ephem-wheel-cache-1klnwuaa/wheels/1e/cb/03/20479d63812e4a01da92afa8753f6ad37f87806c24a620aaa0
         Building wheel for cornice-swagger (setup.py): started
         Building wheel for cornice-swagger (setup.py): finished with status 'done'
         Created wheel for cornice-swagger: filename=cornice_swagger-0.7.0-py3-none-any.whl size=32113 sha256=90731351951a9535a8b7ff2999501b0af78ce42d82c5780872576bfed066c842
         Stored in directory: /tmp/pip-ephem-wheel-cache-1klnwuaa/wheels/d3/97/85/8f0d11de3c7e4c46a9a537b88cb052406d59d2fe091d327eaa
         Building wheel for logging-color-formatter (setup.py): started
         Building wheel for logging-color-formatter (setup.py): finished with status 'done'
         Created wheel for logging-color-formatter: filename=logging_color_formatter-1.0.2-py3-none-any.whl size=5018 sha256=d688e816cfff8f636084c7f94ff932424152d82e945c8569789e07b773a06aca
         Stored in directory: /tmp/pip-ephem-wheel-cache-1klnwuaa/wheels/ff/82/a8/6f815f8f05ee45605f75a422128c330b43e0db94fc6b1ee492
         Building wheel for simplejson (setup.py): started
         Building wheel for simplejson (setup.py): finished with status 'done'
         Created wheel for simplejson: filename=simplejson-3.17.0-cp36-cp36m-linux_x86_64.whl size=123790 sha256=976ee1a38a9db7f41c46aa83bcf71aaac356c80489c8405a89894465a0a49538
         Stored in directory: /tmp/pip-ephem-wheel-cache-1klnwuaa/wheels/c2/95/a2/477b46cfe980061fddc4cb76ed4657eceec35d2b2090355e41
         Building wheel for pyrsistent (setup.py): started
         Building wheel for pyrsistent (setup.py): finished with status 'done'
         Created wheel for pyrsistent: filename=pyrsistent-0.16.0-cp36-cp36m-linux_x86_64.whl size=115056 sha256=1b300227b03a30954980f656503fa96a6e105e09284d887b8854c540432fa5ac
         Stored in directory: /tmp/pip-ephem-wheel-cache-1klnwuaa/wheels/d1/8a/1c/32ab9017418a2c64e4fbaf503c08648bed2f8eb311b869a464
       Successfully built kinto SQLAlchemy psycopg2 cornice-swagger logging-color-formatter simplejson pyrsistent
       Installing collected packages: pycparser, cffi, six, bcrypt, translationstring, iso8601, colander, venusian, simplejson, webob, zope.interface, plaster, PasteDeploy, plaster-pastedeploy, hupper, zope.deprecation, pyramid, cornice, cornice-swagger, dockerflow, zipp, importlib-metadata, attrs, pyrsistent, jsonschema, jsonpointer, jsonpatch, colorama, logging-color-formatter, python-dateutil, pyramid-multiauth, transaction, pyramid-tm, certifi, urllib3, idna, chardet, requests, waitress, ujson, kinto, SQLAlchemy, psycopg2, zope.sqlalchemy
       Successfully installed PasteDeploy-2.1.0 SQLAlchemy-1.3.15 attrs-19.3.0 bcrypt-3.1.7 certifi-2019.11.28 cffi-1.14.0 chardet-3.0.4 colander-1.7.0 colorama-0.4.3 cornice-4.0.1 cornice-swagger-0.7.0 dockerflow-2019.10.0 hupper-1.10.2 idna-2.9 importlib-metadata-1.6.0 iso8601-0.1.12 jsonpatch-1.25 jsonpointer-2.0 jsonschema-3.2.0 kinto-9.1.2 logging-color-formatter-1.0.2 plaster-1.0 plaster-pastedeploy-0.7 psycopg2-2.8.4 pycparser-2.20 pyramid-1.10.4 pyramid-multiauth-0.9.0 pyramid-tm-2.4 pyrsistent-0.16.0 python-dateutil-2.8.1 requests-2.23.0 simplejson-3.17.0 six-1.14.0 transaction-3.0.0 translationstring-1.3 ujson-2.0.3 urllib3-1.25.8 venusian-3.0.0 waitress-1.4.3 webob-1.8.6 zipp-3.1.0 zope.deprecation-4.4.0 zope.interface-5.0.1 zope.sqlalchemy-1.3
-----> Running post-compile hook
Traceback (most recent call last):
  File "/app/.heroku/python/bin/kinto", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.6/site-packages/kinto/__main__.py", line 159, in main
    env = bootstrap(config_file)
  File "/app/.heroku/python/lib/python3.6/site-packages/pyramid/paster.py", line 111, in bootstrap
    app = get_app(config_uri, options=options)
  File "/app/.heroku/python/lib/python3.6/site-packages/pyramid/paster.py", line 30, in get_app
    return loader.get_wsgi_app(name, options)
  File "/app/.heroku/python/lib/python3.6/site-packages/plaster_pastedeploy/__init__.py", line 129, in get_wsgi_app
    global_conf=defaults,
  File "/app/.heroku/python/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/app/.heroku/python/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/app/.heroku/python/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/app/.heroku/python/lib/python3.6/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/app/.heroku/python/lib/python3.6/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/app/.heroku/python/lib/python3.6/site-packages/kinto/__init__.py", line 51, in main
    default_settings=DEFAULT_SETTINGS)
  File "/app/.heroku/python/lib/python3.6/site-packages/kinto/core/initialization.py", line 575, in initialize
    config.include('kinto.core', route_prefix=api_version)
  File "/app/.heroku/python/lib/python3.6/site-packages/pyramid/config/__init__.py", line 676, in include
    c(configurator)
  File "/app/.heroku/python/lib/python3.6/site-packages/kinto/core/__init__.py", line 190, in includeme
    step_func(config)
  File "/app/.heroku/python/lib/python3.6/site-packages/kinto/core/initialization.py", line 216, in setup_storage
    backend = storage_mod.load_from_config(config)
  File "/app/.heroku/python/lib/python3.6/site-packages/kinto/core/storage/postgresql/__init__.py", line 921, in load_from_config
    client = create_from_config(config, prefix='storage_')
  File "/app/.heroku/python/lib/python3.6/site-packages/kinto/core/storage/postgresql/client.py", line 76, in create_from_config
    from zope.sqlalchemy import ZopeTransactionExtension, invalidate
ImportError: cannot import name 'ZopeTransactionExtension'
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by glasserc** [comment]
Hmm, kinto 9.1.2 is quite old. I guess this repository isn't really good for much of anything besides an example. It might work for you if you try a newer version, such as 13.6.5, instead.

**Comment by searchy2** [comment]
Thanks for taking a look! It would be great if someone could update this repo to make it work with Heroku. It really sucks to not have the 1-click deploy working so people can easily try it out.

**Comment by Natim** [comment]
@searchy2 could you try again?

**Comment by Natim** [comment]
I just tried with my fixes and it works. Thank you for the ping.
