### ISSUE TITLE
Python Version and SQLAlchemy Issues

### ISSUE THREAD

**Issue by StealthStartupLabs** [Kinto/kinto-heroku#25]
I get an error when following the instructions in README.md. I started with the 'Deploy to Heroku' button on the [Install Kinto page](https://docs.kinto-storage.org/en/stable/tutorials/install.html) of the doc. That failed with a Python version error, so I found this repo. I checked the Heroku Python docs and saw that python-3.8.10 is supported on the Heroku-20 stack. So I changed the runtime.txt version to python-3.8.10 which got me farther along in the process. However, I'm still getting the following error in the 'post-compile hook':

```
remote: -----> Running post-compile hook
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/bin/kinto", line 8, in <module>
remote:     sys.exit(main())
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/kinto/__main__.py", line 216, in main
remote:     env = bootstrap(config_file, options={"command": "migrate"})
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/pyramid/paster.py", line 117, in bootstrap
remote:     app = get_app(config_uri, options=options)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/pyramid/paster.py", line 30, in get_app
remote:     return loader.get_wsgi_app(name, options)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/plaster_pastedeploy/__init__.py", line 125, in get_wsgi_app
remote:     return loadapp(
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
remote:     return loadobj(APP, uri, name=name, **kw)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
remote:     return context.create()
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 715, in create
remote:     return self.object_type.invoke(self)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
remote:     return fix_call(context.object, context.global_conf, **context.local_conf)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/paste/deploy/util.py", line 55, in fix_call
remote:     val = callable(*args, **kw)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/kinto/__init__.py", line 51, in main
remote:     kinto.core.initialize(config, version=__version__, default_settings=DEFAULT_SETTINGS)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/kinto/core/initialization.py", line 581, in initialize    
remote:     config.include("kinto.core", route_prefix=api_version)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/pyramid/config/__init__.py", line 666, in include
remote:     c(configurator)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/kinto/core/__init__.py", line 197, in includeme
remote:     step_func(config)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/kinto/core/initialization.py", line 222, in setup_storage 
remote:     backend = storage_mod.load_from_config(config)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/kinto/core/storage/postgresql/__init__.py", line 998, in load_from_config
remote:     client = create_from_config(config, prefix="storage_")
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/kinto/core/storage/postgresql/client.py", line 107, in create_from_config
remote:     engine = sqlalchemy.engine_from_config(filtered_settings, prefix=prefix, url=url)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 743, in engine_from_config
remote:     return create_engine(url, **options)
remote:   File "<string>", line 2, in create_engine
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned     
remote:     return fn(*args, **kwargs)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine  
remote:     entrypoint = u._get_entrypoint()
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint   
remote:     cls = registry.load(name)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load        
remote:     raise exc.NoSuchModuleError(
remote: sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
```

This is outside my wheelhouse otherwise I would create a PR for a fix. Any help resolving this would be greatly appreciated. Also, once the fix is committed, it would be awesome if the 'Deploy to Heroku' button on the [Install Kinto page](https://docs.kinto-storage.org/en/stable/tutorials/install.html) could be fixed.

Thanks in advance for your help!

**Comment by Natim** [comment]
I tried to fix this with #27 can you try again?
